defaults: &defaults
  adapter:  mysql
  encoding: utf8
  username: bort
  password: 'gem-grade1234'
  host:     localhost
  #pool: 5
  
development:
  database: bort_development
  <<: *defaults

test:
  database: bort_test
  <<: *defaults
  
staging:
  database: bort_staging
  <<: *defaults
  
production:
  database: bort
  <<: *defaults
